### ISSUE TITLE
EDA: table right click improvements

### ISSUE THREAD

**Issue by SmiteDeluxe** [Safe-DS/DSL#1180]
### Is your feature request related to a problem?

Unintuitive that:
- No row right clicks
- Two column plotting by selection while one column by current right clicked column
- No right clicks on table cells

### Desired solution

- Row right clicks for selections
- Submenus in column right click:
     - "Plot Selection" if one or two selected => plot from selected columns
     - "Plot Column" that plots one column plots on current right clicked columns
- "Plot Selection" also possible if right click on cells

**Comment by lars-reimann** [comment]
It might also be helpful to show the two-column plots if only one column is selected, e.g. as "x-column of scatterplot". Then the dialog for plot generation opens with the plot and x-column prefilled and the user must only pick a y-column.

**Comment by SmiteDeluxe** [comment]
@lars-reimann not implementing above for now because of additional work it would need. But I do show tooltips to let users know what they have to do to plot
