### ISSUE TITLE
@PythonCall annotation for functions

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/DSL#617]
### Is your feature request related to a problem?

For some functions, we might want to offer a different interface than Python offers. For example, we might want to replace the Python code `', '.join([1, 2])` with `[1, 2].join(', ')`.

### Desired solution

An annotation `@PythonCall` that is evaluated by the code generator that specifies how code should be rewritten. The annotation takes a string that can have placeholder that point either to `this` or a parameter. Example:

```
class List {
    @PythonCall("$delimiter.join($this)")
    fun join(delimiter: String) -> String
}
```

The code generator can then replace the placeholders with the actual values of `this` and the parameters. For the call `[1, 2].join(', ')`, it would then generate the Python code `', '.join([1, 2])`.

**Comment by lars-reimann** [comment]
@WinPlay02 Would this be something you could work on?

**Comment by WinPlay02** [comment]
Sure, I'll try to implement the desired solution
