### ISSUE TITLE
No feedback if runner command is wrong

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/DSL#909]
### Describe the bug

If a runner with an incorrect version is installed, a popup is shown to the user. If the extension is started with an incorrect runner command, however, no popup is displayed and nothing is logged. Moreover, changes to the runner command have no effect until the extension is restarted.

### To Reproduce

1. Set `safe-ds-runner-test` as the runner command.
2. Restart the extension host.
3. Open some Safe-DS file.

### Expected behavior

1. A popup should be shown.
2. Something should be logged.
3. Changes to the runner command should lead to another attempt to start it.

**Comment by lars-reimann** [comment]
@WinPlay02 Do you have an idea why this is happening? Might be related to #853.

**Comment by WinPlay02** [comment]
For some reason, the `close` event is no longer fired (if it ever was), and the `error` event is now relevant for handling a wrong command.
The update (`updateRunnerCommand`) command was added to the runner component for the refactoring, but I forgot to actually call it, this is now fixed in #914
