### ISSUE TITLE
EDA: Remove old vs-code states

### ISSUE THREAD

**Issue by SmiteDeluxe** [Safe-DS/DSL#986]
### Is your feature request related to a problem?

Currently the global vs-code state fills up over time making certain operations slow.

### Desired solution

The goal is to save the Date of last update along with the State in the global state. Then in the findCurrentState method where those states are iterated once on a new panel startup anyway, the AST should be searched for the placeholder and pipeline name of the old states and in case it does not find that combination AND the states last update is more than a day ago, it should remove that state from the global state.

### Possible alternatives (optional)

Just remove if older than 7 days and do not care about the placeholder existence.

**Comment by SmiteDeluxe** [comment]
@lars-reimann do you know how to best search for a placeholder in the AST given the pipeline name and placeholder name?

**Comment by lars-reimann** [comment]
OK, the most robust way requires three pieces of information:

1. The URI of the document that contains the pipeline.
2. The name of the pipeline.
3. The name of the placeholder.

Then

1. Get the document by URI: `const document = services.shared.workspace.LangiumDocuments.getDocument(uri)`
2. Get the module: `const module = <SdsModule>document.parseResult.value`
3. Find the pipeline with the given name: `const pipeline module.getModuleMembers().find(it => isSdsPipeline(it) && it.name === ...`
4. Find the placeholder in the pipeline: `const placeholder = getPlaceholderByName(pipeline.body, ...)`

**Comment by SmiteDeluxe** [comment]
I see the value in that, yes @lars-reimann. Of course the caching here is not just that what the Runner is doing or should be doing as it is a lot about the action history, but I agree on that it can be a bit counter intuitive. By not having the global state we are taking away some efficiency and usability in one area and adding safety and usability in another aspect. Although the gain in usability might be of more value here as you say, maybe not for new users that have simple pipelines and work slowly but certainly for those that have big pipelines that change a lot.

**Comment by lars-reimann** [comment]
Let's talk about that tomorrow.
